name: Build command index
on:
  push:
    branches:
      - main

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build index
        run: |
          bash build/extract_commands.sh > commands.txt

      - name: Show output
        run: |
          cat commands.txt

      - name: Publish index
        uses: actions/upload-artifact@v2
        with:
          name: commands
          path: commands.txt
